[package]
name = "komorebic"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
komorebi-core = { path = "../komorebi-core" }

clap = "3.0.0-beta.2"
dirs = "3"
powershell_script = "0.1.5"
uds_windows = "1"
color-eyre = "0.5.11"